### PR TITLE
Updates to simgear - 2017.2.1

### PR DESCRIPTION
**Pull request by adhefe**

### CODE REVIEW

**Review by tpgxyz — CHANGES_REQUESTED** [review]
Please remove from Pull Request this file

simgear-2017.2.1.tar.bz2

We are not allowing to keep in github binary files.

Please upload this file to file-store.openmandriva.org

**Comment by adhefe** [comment]
Didn't I already uploaded this file to file-store.openmandriva.com?

Also, I don't know how to remove a file from pull request. I will try to
find out how...

Em 11/09/2017 4:58 AM, "Tomasz Paweł Gajc" <notifications@github.com>
escreveu:

*@tpgxyz* requested changes on this pull request.

Please remove from Pull Request this file

simgear-2017.2.1.tar.bz2

We are not allowing to keep in github binary files.

Please upload this file to file-store.openmandriva.org

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenMandrivaAssociation/simgear/pull/1#pullrequestreview-61740128>,
or mute the thread

**Comment by tpgxyz** [comment]
@adhefe  You need to prepare new PR, without this commit https://github.com/OpenMandrivaAssociation/simgear/pull/1/commits/49b943f808fec864b3d9a71b03524c6a61d83ca4

**Comment by adhefe** [comment]
Hope to have done it right this time. I've asked for "New Pull Request" at
gitHub but did not see any "confirmation" button(???).

2017-09-11 7:19 GMT-03:00 Tomasz Paweł Gajc <notifications@github.com>:

**Pull request merged**
